// src/app/search/listing-card/listing-progress-bar/listing-progress-bar.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'listing-progress-bar',
    standalone: true,
    imports: [],
    template: `
    <div class="progress" style="height: 2px">
            <div
                class="progress-bar"
                role="progressbar"
                [style]="{'width': progress + '%'}"
                aria-valuenow={progress}
                aria-valuemin={min}
                aria-valuemax={max}
            >
            </div>
        </div>
  `,
    styles: ``
})
export class ListingProgressBarComponent {

    @Input() dateListed: string = '';
    @Input() auctionScheduleTime?: string = '';

    progress: number = 0;

    ngOnInit() {
        if (this.dateListed == '' || this.dateListed == null || this.auctionScheduleTime == '' || this.auctionScheduleTime == null)
            return;

        const msToDaysMultiplier = 1000 * 60 * 60 * 24;

        const dateListedDays = Math.round(new Date(this.dateListed).getTime() / msToDaysMultiplier);
        const auctionDateDays = this.auctionScheduleTime ? Math.round(new Date(this.auctionScheduleTime).getTime() / msToDaysMultiplier) : 0;
        const nowDays = Math.round(new Date().getTime() / msToDaysMultiplier);

        this.progress = Math.round((auctionDateDays > 0 ? ((nowDays - dateListedDays) / (auctionDateDays - dateListedDays)) : 0) * 100);
    }

}

// src/components/listingProgressBar/index.tsx
import React from 'react';
import './listingProgressBar.scss';

function ListingProgressBar(props: {
    id: string,
    dateListed: string,
    auctionScheduleTime?: string
}) {
    const { id, dateListed, auctionScheduleTime } = props;

    const msToDaysMultiplier = 1000 * 60 * 60 * 24;

    const dateListedDays = Math.round(new Date(dateListed).getTime() / msToDaysMultiplier);
    const auctionDateDays = auctionScheduleTime ? Math.round(new Date(auctionScheduleTime).getTime() / msToDaysMultiplier) : 0;
    const nowDays = Math.round(new Date().getTime() / msToDaysMultiplier);

    const min = 0;
    const max = 100;
    const progress = Math.round((auctionDateDays > 0 ? ((nowDays - dateListedDays) / (auctionDateDays - dateListedDays)) : 0) * 100);

    return (
        <React.Fragment key={id}>
            <div className="progress" style={{height: "2px"}}>
                    <div
                        className="progress-bar"
                        role="progressbar"
                        style={{width: `${progress}%`}}
                        aria-valuenow={progress}
                        aria-valuemin={min}
                        aria-valuemax={max}
                    >
                    </div>
                </div>
        </React.Fragment>
    );
}

export default ListingProgressBar;
