// src/app/footer/footer.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'footer',
    standalone: true,
    imports: [],
    template: `
        <div id="footer" class="text-center mb-2 p-2">
            <p class="mb-0">
                &copy; 2024 <a target="_blank" href="https://github.com/scottabutler/">Scott Butler</a>. This site uses API data from <a target="_blank" href="https://developer.domain.com.au/docs/introduction">Domain</a> and is subject to their <a href="https://developer.domain.com.au/docs/support/terms">terms of use</a>.
            </p>
            <p class="mb-0">
                Agency logos and colours are supplied by Domain and remain the property of their respective agency.
            </p>
            <p class="mb-2">
                Your search filters and hidden properties are saved in local storage and do not leave your browser.
            </p>
            <p class="mb-0">
                Icons provided by <a target="_blank" href="https://fontawesome.com/">FontAwesome</a>.
            </p>
            <p class="mb-2">
                Suburb list provided by <a target="_blank" href="https://github.com/michalsn/australian-suburbs">michalsn/australian-suburbs</a>.
            </p>
            <p class="mb-0">
                {{metadata}}
            </p>
        </div>
  `,
    styles: ``
})
export class FooterComponent {
    @Input() metadata: string = '';
}

// src/components/footer/index.tsx
import React from 'react';
import NewTabLink from '../newTabLink'

function Footer() {
    return (
        <>
            <div id="footer" className="text-center mb-2 p-2">
                <p className="mb-0">
                    &copy; 2022 <NewTabLink href="https://github.com/scottabutler/" label="Scott Butler" />. This site uses API data from <NewTabLink href="https://developer.domain.com.au/docs/introduction" label="Domain" /> and is subject to their <NewTabLink href="https://developer.domain.com.au/docs/support/terms" label="terms of use" />.
                </p>
                <p className="mb-0">
                    Agency logos and colours are supplied by Domain and remain the property of their respective agency.
                </p>
                <p className="mb-2">
                    Your search filters and hidden properties are saved in local storage and do not leave your computer.
                </p>
                <p className="mb-0">
                    Typeahead component provided by <NewTabLink href="https://ericgio.github.io/react-bootstrap-typeahead/" label="React Bootstrap Typeahead" />.
                </p>
                <p className="mb-0">
                    Icons provided by <NewTabLink href="https://fontawesome.com/" label="FontAwesome" /> and bundled using <NewTabLink href="http://fontello.com/" label="Fontello" />.
                </p>
                <p className="mb-0">
                    Suburb list provided by <NewTabLink href="https://github.com/michalsn/australian-suburbs" label="michalsn/australian-suburbs" />.
                </p>
            </div>
        </>
    );
}

export default Footer;
