// src/components/numericSearchField/index.tsx
import React from 'react';

function NumericSearchField(props: any) {
    const { defaultValue, updateHandler, interval, icon, type } = props;

    const decrement = function() {
        if (defaultValue - interval >= 0) {
            updateHandler(defaultValue - interval);
        }
    }

    const increment = function() {
        updateHandler(defaultValue + interval);
    }

    let text = defaultValue.toLocaleString();
    switch (type) {
        case "min":
            text = `${text}+`;
            break;
        case "max":
            text = `<${text}`;
            break;
    }

    return (
        <>
            <div className="row numeric-search-field mb-2">
                <div className="col-lg-12 align-bottom controls mt-2">
                    <button className="down bg-light text-dark p-1 border border-secondary rounded-left d-inline-block" onClick={decrement}>-</button>
                    <span className="value px-2 py-1 border-top border-bottom border-secondary d-inline-block"><i className={`${icon} float-left`} />{text}</span>
                    <button className="up bg-light text-dark p-1 border border-secondary rounded-right d-inline-block" onClick={increment}>+</button>
                </div>
            </div>
        </>
    );
}

export default NumericSearchField;

// src/app/search/numeric-search-field/numeric-search-field.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
    selector: 'numeric-search-field',
    standalone: true,
    imports: [],
    template: `
    <div class="col-sm-6 col-md-4 col-lg-3 col-xl-12 numeric-search-field mb-2">
        <div class="align-bottom controls px-0">
            <button class="down bg-light text-dark p-1 border border-secondary rounded-start d-inline-block" (click)="decrement()">-</button>
            <span class="value px-2 py-1 border-top border-bottom border-secondary d-inline-block"><i [class]="icon" class="float-start"></i>{{ prefix }}{{ defaultValue.toLocaleString() }}{{ suffix }}</span>
            <button class="up bg-light text-dark p-1 border border-secondary rounded-end d-inline-block"  (click)="increment()">+</button>
        </div>
    </div>
    `,
    styles: `
        .numeric-search-field {
            width: 100%;

            .controls {
                max-width: 250px;
            }

            .value {
                min-width: 60%;
                text-align: center;
            }
            .down,
            .up {
                min-width: 20%;
                text-align: center;
                cursor: pointer;
            }
        }
    `
})
export class NumericSearchFieldComponent {
    @Input() defaultValue: number = 0;
    @Input() interval: number = 1;
    @Input() icon: string = '';
    @Input() type: string = '';
    @Input() prefix: string = '';
    @Input() suffix: string = '';
    @Input() updateHandler: (i: number) => void = () => { };

    @Output() defaultValueChange = new EventEmitter<number>();

    decrement() {
        if (this.defaultValue - this.interval >= 0) {
            this.defaultValueChange.emit(this.defaultValue - this.interval);
        }
    }

    increment() {
        this.defaultValueChange.emit(this.defaultValue + this.interval);
    }

}
