// src/components/simpleCarousel/index.tsx
import React from 'react';
import { useState } from 'react';
import './simpleCarousel.scss';

function SimpleCarousel(props: { id: string, urls: string[], altText: string }) {
    const {
        id, urls, altText
    } = props;

    const [index, setIndex] = useState(0);
    const count = urls.length;
    const previousIndex = getPreviousIndex(index, count);
    const nextIndex = getNextIndex(index, count)
    const dots = urls.map((x, i) => {
        const icon = i === index ? "circle" : "circle-empty";
        return <i key={`dot_${id}_${i}`}className={`icon-${icon}`} />
    });
    const imgStyle = urls[index]
    ? {
        backgroundImage: `url('${urls[index]}')`,
    }
    : {};

    /* Preload adjacent images to prevent flicker on scroll */
    const previousImage = <img src={urls[previousIndex]} style={{display: "none"}} />
    const nextImage = <img src={urls[nextIndex]} style={{display: "none"}} />

    return (
        <div className="wrapper" key={id}>
            {previousImage}{nextImage}
            <div className="img" style={imgStyle} title={altText} />
            <div className="dots">
                <span>{dots}</span>
            </div>
            {urls.length > 1 &&
            <React.Fragment>
                <button className="back-button" onClick={() => { setIndex(previousIndex) }}>
                    <i className="icon-left-open" />
                </button>
                <button className="next-button" onClick={() => { setIndex(nextIndex) }}>
                    <i className="icon-right-open" />
                </button>
            </React.Fragment>
            }
        </div>
    );
}

export default SimpleCarousel;

function getPreviousIndex(current: number, count: number) {
    return current === 0 ? count-1 : current-1;
}
function getNextIndex(current: number, count: number) {
    return current === count-1 ? 0 : current+1;
}

// src/app/search/listing-card/simple-carousel/simple-carousel.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'simple-carousel',
  standalone: true,
  imports: [],
  template: `
        <div class="wrapper">
            <img src={{urls[getPrevIndex()]}} [style]="{'display': 'none'}" alt="Previous carousel" />
            <img src={{urls[getNextIndex()]}} [style]="{'display': 'none'}" alt="Next carousel" />
            <div class="img" [style]="urls[index] && {'backgroundImage': 'url(' + urls[index] + ')'}" [title]="altText"> </div>
            <div class="dots">
                <span>
                    @for (u of urls; track u; let i = $index) {
                    <i [class]="{'icon-circle': i === index, 'icon-circle-empty': i != index}"></i>                    
                    }
                </span>
            </div>
            
            @if (urls.length > 1) {
                <button class="back-button" (click)="goPrev()">
                    <i class="icon-left-open"></i>
                </button>
                <button class="next-button" (click)="goNext()">
                    <i class="icon-right-open"></i>
                </button>
            }
        </div>
  `,
  styleUrl: './simple-carousel.component.scss'
})
export class SimpleCarouselComponent {

    @Input() urls: string[] = [];
    @Input() altText: string = '';

    index: number = 0;
    count: number = 0;
  
    ngOnInit() {
        this.count = this.urls.length;
    }

    getNextIndex(): number {
        return this.index === this.count - 1 ? 0 : this.index + 1;
    }

    getPrevIndex(): number {
        return this.index === 0 ? this.count - 1 : this.index - 1;
    }    

    goNext() {
        this.index = this.getNextIndex();
    }

    goPrev() {
        this.index = this.getPrevIndex(); 
    }
}
